clear all

%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\dunch\Documents\MATLAB\actigraphs\subject_1469.flex.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2016/11/07 14:04:55

%% Initialize variables.
filename = 'C:\Users\dunch\Documents\MATLAB\actigraphs\subject_1469.flex.csv';
delimiter = ',';

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'EmptyValue' ,NaN, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
flexDate = dataArray{:, 1};
flexSteps = dataArray{:, 2};


%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;


dates = datenum(datetime(flexDate, 'ConvertFrom', 'posixtime'));

nov1 = datenum([2016 11 1 0 0 0]);
del = find(dates<nov1);
dates(del) = [];
flexSteps(del) = [];
for n = 1 : length(dates)
    dv = datevec(dates(n));
    hours(n) = dv(4)+dv(5)/60+dv(6)/3600;
    days(n) = dv(3); 
end

days = days - days(1)+5;

figure
hold on
theta = -hours *2*pi/24 +pi/2;
hold on
axis square
x = days.*cos(theta);
y = days.*sin(theta);
for n = 1 : length(x)
    
    if flexSteps(n) > 0
        c = flexSteps(n)/max(flexSteps);
        %plot(x(n), y(n),'.','Color',[1,c,c], 'MarkerSize', 22)
        plot(x(n), y(n),'ro','MarkerSize', flexSteps(n)/10)
    end
end
 t = linspace(0, 2*pi, 100);
 plot(13*cos(t), 13*sin(t), 'k')
 plot(15*cos(t), 15*sin(t), 'k')
 for hr = 23:-1 : 0
    t = -hr*2*pi/24 + pi/2;
    
    text(14*cos(t)-0.5, 14*sin(t), num2str(hr))
 end
ax = gca;
ax.YTick = [];
ax.XTick = [];



% loop through all the OADC numbers
import Orcatech.MySQL
import Orcatech.IdArray
import Orcatech.Databases.Subjects
import Orcatech.Databases.AlgorithmResults

o = Orcatech.Interface('rileyt','feb=21');
MySQL.connect(Subjects.SERVER);

query1 = 'SELECT Stamp ';
query2 = 'FROM NYCEData.home_1353 ';
query3 = ['WHERE Event = 32 AND Sensor = ''000D6F000409133A'''];
query = [query1 query2 query3];
[Stamp] = mysql(query);
Stamp = Stamp + 7/24;


datestr1 = datenum([2016 11 01 0 0 0]);
datestr2 = datenum([2016 11 08 0 0 0]);

del = find(Stamp < datestr1 | Stamp > datestr2);
Stamp(del) = [];
events = ones(size(Stamp));
% subplot(4,1,4)
% hold on
% plot(Stamp, events, 'o')
% datetick('x')
% title('Apartment Sensor Firings')

query1 = 'SELECT Stamp ';
query2 = 'FROM NYCEData.home_1353 ';
query3 = ['WHERE Event = 32 AND Sensor = ''000D6F0004B0EC47'''];
query = [query1 query2 query3];
[Stamp] = mysql(query);
Stamp = Stamp + 7/24;


datestr1 = datenum([2016 11 01 0 0 0]);
datestr2 = datenum([2016 11 08 0 0 0]);

del = find(Stamp < datestr1 | Stamp > datestr2);
Stamp(del) = [];
events = ones(size(Stamp));
% subplot(4,1,4)
% plot(Stamp, events, 'ro')
% datetick('x')
% title('Apartment Sensor Firings')


 clear hours days
for n = 1 : length(Stamp)
    dv = datevec(Stamp(n));
    hours(n) = dv(4)+dv(5)/60+dv(6)/3600;
    days(n) = dv(3); 
end
daysweek = unique(days);
days = days - days(1)+5;

hold on
theta = -hours *2*pi/24+pi/2+7+pi;
hold on
axis square

x = days.*cos(theta);
y = days.*sin(theta);
for n = 1 : length(x)
    plot(x(n), y(n),'bo')
%     if flexSteps(n) > 0
%         c = flexSteps(n)/max(flexSteps);
%         %plot(x(n), y(n),'.','Color',[1,c,c], 'MarkerSize', 22)
%         plot(x(n), y(n),'ro','MarkerSize', flexSteps(n)/10)
%     end
end

query1 = 'SELECT Stamp ';
query2 = 'FROM NYCEData.home_1353 ';
query3 = ['WHERE Event = 32 AND Sensor = ''000D6F000409133A'''];
query = [query1 query2 query3];
[Stamp] = mysql(query);
Stamp = Stamp + 7/24;


datestr1 = datenum([2016 11 01 0 0 0]);
datestr2 = datenum([2016 11 08 0 0 0]);

del = find(Stamp < datestr1 | Stamp > datestr2);
Stamp(del) = [];
events = ones(size(Stamp));
% subplot(4,1,4)
% plot(Stamp, events, 'ro')
% datetick('x')
% title('Apartment Sensor Firings')


 clear hours days
for n = 1 : length(Stamp)
    dv = datevec(Stamp(n));
    hours(n) = dv(4)+dv(5)/60+dv(6)/3600;
    days(n) = dv(3); 
end
daysweek = unique(days);
days = days - days(1)+5;

hold on
theta = -hours *2*pi/24+pi/2+7+pi;
hold on
axis square

x = days.*cos(theta);
y = days.*sin(theta);
for n = 1 : length(x)
   % plot(x(n), y(n),'go')
%     if flexSteps(n) > 0
%         c = flexSteps(n)/max(flexSteps);
%         %plot(x(n), y(n),'.','Color',[1,c,c], 'MarkerSize', 22)
%         plot(x(n), y(n),'ro','MarkerSize', flexSteps(n)/10)
%     end
end

daysweekPos = daysweek - daysweek(1)+5;
dayname = {'Tues', 'Wed', 'Thurs', 'Fri', 'Sat', 'Sun', 'Mon'};
for n = 1 : length(daysweekPos)
    %text(daysweekPos(n)-0.2, n, ['11/ ' num2str(daysweek(n))], 'FontSize', 6)
    text(daysweekPos(n)-0.2, n/2, dayname{n}, 'FontSize', 6)
end
mysql('close')

