function [fitresult, gof] = createFit(night, weeklyMedianIntactTST)
%CREATEFIT(NIGHT,WEEKLYMEDIANINTACTTST)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : night
%      Y Output: weeklyMedianIntactTST
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 16-Nov-2016 12:47:23


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( night, weeklyMedianIntactTST );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'weeklyMedianIntactTST vs. night', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel night
ylabel weeklyMedianIntactTST
grid on


