function [fitresult, gof] = createFitWeeklyAMCI(weekAmciStarts, weeklyMedianAmciTST)
%CREATEFIT(WEEKAMCISTARTS,WEEKLYMEDIANAMCITST)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : weekAmciStarts
%      Y Output: weeklyMedianAmciTST
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 07-Oct-2016 10:44:08


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( weekAmciStarts, weeklyMedianAmciTST );

% Set up fittype and options.
ft = fittype( 'poly5' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'weeklyMedianAmciTST vs. weekAmciStarts', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel weekAmciStarts
ylabel weeklyMedianAmciTST
grid on


