function [fitresult, gof] = createFitTotal(totalDate, totalTime)
%CREATEFIT(TOTALDATE,TOTALTIME)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : totalDate
%      Y Output: totalTime
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 04-Oct-2016 14:35:42


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( totalDate, totalTime );

% Set up fittype and options.
ft = fittype( 'poly4' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'totalTime vs. totalDate', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel totalDate
ylabel totalTime
grid on


