function [fitresult, gof] = SeasonalLatencyFits(intactdates, dailyAverageIntact, amcidates, dailyAverageAmci, namcidates, dailyAverageNamci)
%CREATEFITS1(INTACTDATES,DAILYAVERAGEINTACT,AMCIDATES,DAILYAVERAGEAMCI,NAMCIDATES,DAILYAVERAGENAMCI)
%  Create fits.
%
%  Data for 'untitled fit 1' fit:
%      X Input : intactdates
%      Y Output: dailyAverageIntact
%  Data for 'untitled fit 2' fit:
%      X Input : amcidates
%      Y Output: dailyAverageAmci
%  Data for 'untitled fit 3' fit:
%      X Input : namcidates
%      Y Output: dailyAverageNamci
%  Output:
%      fitresult : a cell-array of fit objects representing the fits.
%      gof : structure array with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 28-Sep-2016 09:08:21

%% Initialization.

% Initialize arrays to store fits and goodness-of-fit.
fitresult = cell( 3, 1 );
gof = struct( 'sse', cell( 3, 1 ), ...
    'rsquare', [], 'dfe', [], 'adjrsquare', [], 'rmse', [] );

%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( intactdates, dailyAverageIntact );

% Set up fittype and options.
ft = fittype( 'poly6' );

% Fit model to data.
[fitresult{1}, gof(1)] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult{1}, xData, yData );
title('Sleep Latency for Cognitively Intact')
% Label axes
datetick('x', 12)
ylabel('Minutes')
grid on

%% Fit: 'untitled fit 2'.
[xData, yData] = prepareCurveData( amcidates, dailyAverageAmci );

% Set up fittype and options.
ft = fittype( 'poly6' );

% Fit model to data.
[fitresult{2}, gof(2)] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'untitled fit 2' );
h = plot( fitresult{2}, xData, yData );
title('Sleep Latency for Amnestic MCI')
% Label axes
datetick('x', 12)
ylabel('Minutes')
grid on

%% Fit: 'untitled fit 3'.
[xData, yData] = prepareCurveData( namcidates, dailyAverageNamci );

% Set up fittype and options.
ft = fittype( 'poly6' );

% Fit model to data.
[fitresult{3}, gof(3)] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'untitled fit 3' );
h = plot( fitresult{3}, xData, yData );
title('Sleep Latency for Nonamnestic MCI')
% Label axes
datetick('x', 12)
ylabel('Minutes')
grid on


